server:
  port: 1020
com:
  bcm:
    app-db-v2:
      url: ${V2_DATABASE_URL:jdbc:mysql://localhost:6033/bcmv2?createDatabaseIfNotExist=true}
      username: ${V2_DATABASE_USER:root}
      password: ${V2_DATABASE_PASSWORD:secret}
      driver-class-name: ${V2_DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
    app-db-v1:
      url: ${V1_DATABASE_URL:jdbc:sqlserver://LAPTOP\SQLEXPRESS:1433;database=bcm;encrypt=false;trustServerCertificate=false;integratedSecurity=true}
      username: ${V1_DATABASE_USER:}
      password: ${V1_DATABASE_PASSWORD:}
      driver-class-name: ${V1_DATABASE_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show-sql: false
        format-sql: false
        hbm2ddl:
          auto: update
      package-scan: com.itmaxglobal.bcmmigrationsync.bcmv1.entity
      hikari:
        maximum-pool-size: 8 # Maximum number of connections
        minimum-idle: 5       # Minimum number of idle connections
        idle-timeout: 30000   # Idle timeout in milliseconds
        max-lifetime: 1800000 # Maximum lifetime of a connection in milliseconds
    goLiveDate: "2024-02-09 00:00:00" # go live date
    email:
      from: # from
      to: # to
    host-name: Bcmv2 Migration Server
    host-address: 10.0.150.76
    email-send-time: 30.0

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  # Batch processing
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
    chunk-size: 10000
    page-size: 10000
    fetch-size: 10000
    #core-pool-size: 2
    #max-pool-size: 2
    jobCheck: true

  # SMTP Properties
  mail:
    host: smtp.gmail.com
    username: # username
    password: # password
    port: 587
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false